import { Card } from '@/app/components/ui/card';
import { Button } from '@/app/components/ui/button';
import { Input } from '@/app/components/ui/input';
import { Label } from '@/app/components/ui/label';
import { Switch } from '@/app/components/ui/switch';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/app/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/app/components/ui/select';
import { useTranslation } from 'react-i18next';

export function Settings() {
  const { t } = useTranslation('settings');

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl mb-2">{t('title')}</h1>
        <p className="text-muted-foreground">{t('subtitle')}</p>
      </div>

      <Tabs defaultValue="general" className="w-full">
        <TabsList>
          <TabsTrigger value="general">{t('tabs.general')}</TabsTrigger>
          <TabsTrigger value="security">{t('tabs.security')}</TabsTrigger>
          <TabsTrigger value="performance">{t('tabs.performance')}</TabsTrigger>
          <TabsTrigger value="notifications">{t('tabs.notifications')}</TabsTrigger>
        </TabsList>

        <TabsContent value="general" className="space-y-4">
          <Card className="p-6">
            <h3 className="mb-4">{t('sections.platformInfo')}</h3>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label>{t('labels.platformName')}</Label>
                <Input defaultValue="EDA Platform" />
              </div>
              <div className="space-y-2">
                <Label>{t('labels.adminEmail')}</Label>
                <Input type="email" defaultValue="admin@example.com" />
              </div>
              <div className="space-y-2">
                <Label>{t('labels.timezone')}</Label>
                <Select defaultValue="asia-shanghai">
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="asia-shanghai">{t('timezones.asiaShanghai')}</SelectItem>
                    <SelectItem value="utc">{t('timezones.utc')}</SelectItem>
                    <SelectItem value="america-new-york">{t('timezones.americaNewYork')}</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </Card>

          <Card className="p-6">
            <h3 className="mb-4">{t('sections.featureToggles')}</h3>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <Label>{t('toggles.autoGenerateDocs.label')}</Label>
                  <p className="text-sm text-muted-foreground">{t('toggles.autoGenerateDocs.description')}</p>
                </div>
                <Switch defaultChecked />
              </div>
              <div className="flex items-center justify-between">
                <Label>{t('toggles.sqlOptimizationHints.label')}</Label>
                <Switch defaultChecked />
              </div>
              <div className="flex items-center justify-between">
                <Label>{t('toggles.aiAliasRecommendation.label')}</Label>
                <Switch />
              </div>
            </div>
          </Card>
        </TabsContent>

        <TabsContent value="security" className="space-y-4">
          <Card className="p-6">
            <h3 className="mb-4">{t('sections.securityPolicy')}</h3>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label>{t('labels.defaultAuthMethod')}</Label>
                <Select defaultValue="api-key">
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="api-key">{t('authMethods.apiKey')}</SelectItem>
                    <SelectItem value="oauth2">{t('authMethods.oauth2')}</SelectItem>
                    <SelectItem value="jwt">{t('authMethods.jwt')}</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>{t('labels.sqlSecurityLevel')}</Label>
                <Select defaultValue="strict">
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="strict">{t('sqlSecurityLevels.strict')}</SelectItem>
                    <SelectItem value="normal">{t('sqlSecurityLevels.normal')}</SelectItem>
                    <SelectItem value="loose">{t('sqlSecurityLevels.loose')}</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <Label>{t('toggles.ipWhitelist.label')}</Label>
                  <p className="text-sm text-muted-foreground">{t('toggles.ipWhitelist.description')}</p>
                </div>
                <Switch />
              </div>
              <div className="flex items-center justify-between">
                <Label>{t('toggles.forceHttps.label')}</Label>
                <Switch defaultChecked />
              </div>
            </div>
          </Card>

          <Card className="p-6">
            <h3 className="mb-4">{t('sections.dataMasking')}</h3>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <Label>{t('toggles.autoDetectSensitiveFields.label')}</Label>
                <Switch defaultChecked />
              </div>
              <div className="space-y-2">
                <Label>{t('labels.maskingRuleTemplates')}</Label>
                <div className="text-sm text-muted-foreground">
                  <div>{t('maskingTemplates.phone')}</div>
                  <div>{t('maskingTemplates.idCard')}</div>
                  <div>{t('maskingTemplates.email')}</div>
                </div>
              </div>
            </div>
          </Card>
        </TabsContent>

        <TabsContent value="performance" className="space-y-4">
          <Card className="p-6">
            <h3 className="mb-4">{t('sections.performanceThresholds')}</h3>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label>{t('labels.sqlPerformanceMinScore')}</Label>
                <Input type="number" defaultValue="60" />
                <p className="text-xs text-muted-foreground">{t('hints.sqlPerformanceMinScore')}</p>
              </div>
              <div className="space-y-2">
                <Label>{t('labels.queryTimeoutSeconds')}</Label>
                <Input type="number" defaultValue="30" />
              </div>
              <div className="space-y-2">
                <Label>{t('labels.defaultQpsLimit')}</Label>
                <Input type="number" defaultValue="100" />
              </div>
              <div className="space-y-2">
                <Label>{t('labels.maxReturnRows')}</Label>
                <Input type="number" defaultValue="1000" />
              </div>
            </div>
          </Card>

          <Card className="p-6">
            <h3 className="mb-4">{t('sections.cacheStrategy')}</h3>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <Label>{t('toggles.queryResultCache.label')}</Label>
                <Switch defaultChecked />
              </div>
              <div className="space-y-2">
                <Label>{t('labels.cacheTtlMinutes')}</Label>
                <Input type="number" defaultValue="10" />
              </div>
            </div>
          </Card>
        </TabsContent>

        <TabsContent value="notifications" className="space-y-4">
          <Card className="p-6">
            <h3 className="mb-4">{t('sections.notificationChannels')}</h3>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <Label>{t('channels.email.label')}</Label>
                  <p className="text-sm text-muted-foreground">{t('channels.email.description')}</p>
                </div>
                <Switch defaultChecked />
              </div>
              <div className="flex items-center justify-between">
                <Label>{t('channels.wecom.label')}</Label>
                <Switch />
              </div>
              <div className="flex items-center justify-between">
                <Label>{t('channels.dingtalk.label')}</Label>
                <Switch />
              </div>
            </div>
          </Card>

          <Card className="p-6">
            <h3 className="mb-4">{t('sections.notificationRules')}</h3>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <Label>{t('rules.apiPublish.label')}</Label>
                <Switch defaultChecked />
              </div>
              <div className="flex items-center justify-between">
                <Label>{t('rules.apiUpdate.label')}</Label>
                <Switch defaultChecked />
              </div>
              <div className="flex items-center justify-between">
                <Label>{t('rules.performanceAlert.label')}</Label>
                <Switch defaultChecked />
              </div>
              <div className="flex items-center justify-between">
                <Label>{t('rules.securityIncident.label')}</Label>
                <Switch defaultChecked />
              </div>
            </div>
          </Card>
        </TabsContent>
      </Tabs>

      <div className="flex justify-end gap-2">
        <Button variant="outline">{t('actions.reset')}</Button>
        <Button>{t('actions.save')}</Button>
      </div>
    </div>
  );
}
